version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    container_name: mysql
    volumes:
      - mydb:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    image: vectis-analytics
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  mydb:
